version: '3.8'

services:
  zhirui-website:
    build: .
    container_name: zhirui-business-website
    ports:
      - "80:80"
      - "443:443"  # 如果需要 HTTPS
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # 如果需要自定义 nginx 配置
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 如果需要 SSL 证书
      # - ./ssl:/etc/nginx/ssl:ro
    networks:
      - zhirui-network

networks:
  zhirui-network:
    driver: bridge

# 可选：如果需要数据持久化
# volumes:
#   zhirui_data:
